name: CI/CD Pipeline

on: 
  push:
    branches:
      - tracker

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test  

      # - name: Build Application
      #   run: npm run build 
